### ISSUE TITLE
检测Java代码或xml文件中未写在strings.xml中的字符串

### ISSUE THREAD

**Issue by imyyq-star** [dreamlivemeng/androidstudio-plugins#10]
你好，我想请教一下是否有这么一款插件：
有时候在写代码的时候，有些字符串没有写在strings.xml中，比如：
Toast.makeText(this, "登录失败", Toast.LENGTH_LONG).show();

久而久之，项目中可能就包含了很多类似的情况(因为偷懒且当时没有多国语言化的要求)，如果后期要求多国语言，就会非常麻烦。

所以我想问有没有什么插件是可以检测这些未写在strings.xml中字符串？

**Comment by dreamlivemeng** [comment]
暂时没有，不过你可以通过把Toast封装到父类的Activity或者fragment，然后调用，然后以后可以查找哪些地方使用了这个自定义Toast弹出的方法，分别传入什么参数。
