### ISSUE TITLE
android-drawable-importer源码github地址404

### ISSUE THREAD

**Issue by Kenmmm** [dreamlivemeng/androidstudio-plugins#2]
请更新
[android-drawable-importer](https://github.com/winterDroid/android-drawable-importer-intellij-plugin)
地址https://github.com/winterDroid/android-drawable-importer-intellij-plugin

**Comment by dreamlivemeng** [comment]
@AndrWang 谢谢提出，已更新，如果你在开发有好多插件也可以直接修改提交。

**Comment by Kenmmm** [comment]
还是要谢谢你提供的这么多好用的插件啊
